spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/restaurant
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  jwt:
    secret_key: Java8IsTheBest
    server:
      error:
        include-message: always




